/**
 * withStyleFn — Metro config wrapper for react-native-stylefn
 *
 * Processes your global.css and makes the parsed CSS variables available
 * at runtime via a virtual module that StyleProvider picks up automatically.
 *
 * Usage in metro.config.js:
 *
 *   const { withStyleFn } = require('react-native-stylefn/metro-config');
 *   module.exports = withStyleFn(config, { input: './global.css' });
 */

const path = require('path');
const fs = require('fs');

/**
 * Parses CSS variables from a global.css string.
 * Handles :root (light) and .dark selectors.
 */
function parseCSSVariables(css) {
  const result = { light: {}, dark: {} };
  if (!css || typeof css !== 'string') return result;

  const blockRegex = /([^{]+)\{([^}]*)\}/g;
  let match;

  while ((match = blockRegex.exec(css)) !== null) {
    const selector = (match[1] || '').trim();
    const body = match[2] || '';

    let target = null;
    if (selector === ':root') target = result.light;
    else if (selector === '.dark') target = result.dark;
    else continue;

    const propRegex = /--color-([a-zA-Z0-9-]+)\s*:\s*([^;]+);/g;
    let propMatch;
    while ((propMatch = propRegex.exec(body)) !== null) {
      const name = (propMatch[1] || '').trim();
      const value = (propMatch[2] || '').trim();
      if (name && value) target[name] = value;
    }
  }

  return result;
}

/**
 * Wraps a Metro config to:
 * 1. Read and parse the given CSS file
 * 2. Generate a virtual module `react-native-stylefn/css-vars` with the parsed vars
 * 3. Add a resolver so Metro can find it
 *
 * @param {object} config - Base Metro config
 * @param {object} options
 * @param {string} [options.input='./global.css'] - Path to your CSS file (relative to project root)
 * @returns {object} Updated Metro config
 */
function withStyleFn(config, options = {}) {
  const projectRoot = config.projectRoot || process.cwd();
  const cssInput = options.input || './global.css';
  const cssPath = path.resolve(projectRoot, cssInput);

  // Parse the CSS file
  let parsedCss = { light: {}, dark: {} };
  if (fs.existsSync(cssPath)) {
    try {
      const cssContent = fs.readFileSync(cssPath, 'utf8');
      parsedCss = parseCSSVariables(cssContent);
      console.log('[react-native-stylefn] ✓ Loaded CSS variables from', path.relative(projectRoot, cssPath));
    } catch (err) {
      console.warn('[react-native-stylefn] Failed to parse CSS:', err.message);
    }
  } else {
    console.warn('[react-native-stylefn] CSS file not found:', cssPath);
  }

  // Write the generated virtual module to .stylefn/ directory
  const generatedDir = path.resolve(projectRoot, '.stylefn');
  fs.mkdirSync(generatedDir, { recursive: true });

  const cssVarsFile = path.join(generatedDir, 'css-vars.js');
  fs.writeFileSync(
    cssVarsFile,
    `// Auto-generated by react-native-stylefn — do not edit\nmodule.exports = ${JSON.stringify(parsedCss, null, 2)};\n`
  );

  // Add .stylefn to .gitignore if not already there
  const gitignorePath = path.resolve(projectRoot, '.gitignore');
  if (fs.existsSync(gitignorePath)) {
    const gitignore = fs.readFileSync(gitignorePath, 'utf8');
    if (!gitignore.includes('.stylefn')) {
      fs.appendFileSync(gitignorePath, '\n# react-native-stylefn generated\n.stylefn/\n');
    }
  }

  // Wrap the resolver to map react-native-stylefn/css-vars → generated file
  const existingResolver = config.resolver?.resolveRequest;

  return {
    ...config,
    resolver: {
      ...config.resolver,
      resolveRequest: (context, moduleName, platform) => {
        if (moduleName === 'react-native-stylefn/css-vars') {
          return {
            filePath: cssVarsFile,
            type: 'sourceFile',
          };
        }
        if (existingResolver) {
          return existingResolver(context, moduleName, platform);
        }
        return context.resolveRequest(context, moduleName, platform);
      },
    },
  };
}

module.exports = { withStyleFn };
