/**
 * withStyleFn — Metro config wrapper for react-native-stylefn
 *
 * Processes your global.css and makes the parsed CSS variables available
 * at runtime via a virtual module that StyleProvider picks up automatically.
 *
 * Usage in metro.config.js:
 *
 *   const { withStyleFn } = require('react-native-stylefn/metro-config');
 *   module.exports = withStyleFn(config, { input: './global.css' });
 */

const path = require('path');
const fs = require('fs');

/**
 * Parses CSS variables from a global.css string.
 * Handles :root (light) and .dark selectors.
 *
 * Produces:
 * - light/dark: --color-* variables with prefix stripped (backward compat)
 * - rawVars.light/dark: ALL --* variables with -- prefix stripped (for var() resolution)
 */
function parseCSSVariables(css) {
  const result = { light: {}, dark: {}, rawVars: { light: {}, dark: {} } };
  if (!css || typeof css !== 'string') return result;

  const blockRegex = /([^{]+)\{([^}]*)\}/g;
  let match;

  while ((match = blockRegex.exec(css)) !== null) {
    const selector = (match[1] || '').trim();
    const body = match[2] || '';

    let colorTarget = null;
    let rawTarget = null;

    if (selector === ':root') {
      colorTarget = result.light;
      rawTarget = result.rawVars.light;
    } else if (selector === '.dark') {
      colorTarget = result.dark;
      rawTarget = result.rawVars.dark;
    } else {
      continue;
    }

    // Parse ALL CSS custom properties: --name: value;
    const allPropRegex = /--([a-zA-Z0-9_-]+)\s*:\s*([^;]+);/g;
    let propMatch;
    while ((propMatch = allPropRegex.exec(body)) !== null) {
      const fullName = (propMatch[1] || '').trim();
      const value = (propMatch[2] || '').trim();

      if (!fullName || !value) continue;

      // Store in rawVars (ALL variables)
      rawTarget[fullName] = value;

      // Backward compat: also store --color-* with prefix stripped
      if (fullName.startsWith('color-')) {
        const colorName = fullName.slice(6);
        if (colorName) colorTarget[colorName] = value;
      }
    }
  }

  return result;
}

/**
 * Wraps a Metro config to:
 * 1. Read and parse the given CSS file
 * 2. Generate a virtual module `react-native-stylefn/css-vars` with the parsed vars
 * 3. Add a resolver so Metro can find it
 *
 * @param {object} config - Base Metro config
 * @param {object} options
 * @param {string} [options.input='./global.css'] - Path to your CSS file (relative to project root)
 * @returns {object} Updated Metro config
 */
function withStyleFn(config, options = {}) {
  const projectRoot = config.projectRoot || process.cwd();
  const cssInput = options.input || './global.css';
  const cssPath = path.resolve(projectRoot, cssInput);

  // Parse the CSS file
  let parsedCss = { light: {}, dark: {}, rawVars: { light: {}, dark: {} } };
  if (fs.existsSync(cssPath)) {
    try {
      const cssContent = fs.readFileSync(cssPath, 'utf8');
      parsedCss = parseCSSVariables(cssContent);

      const lightColorCount = Object.keys(parsedCss.light).length;
      const lightRawCount = Object.keys(parsedCss.rawVars.light).length;
      const darkRawCount = Object.keys(parsedCss.rawVars.dark).length;
      console.log(
        `[react-native-stylefn] ✓ Loaded CSS variables from ${path.relative(
          projectRoot,
          cssPath
        )}` +
          ` (${lightRawCount} light vars, ${darkRawCount} dark vars` +
          (lightColorCount > 0 ? `, ${lightColorCount} color vars` : '') +
          ')'
      );
    } catch (err) {
      console.warn('[react-native-stylefn] Failed to parse CSS:', err.message);
    }
  } else {
    console.warn('[react-native-stylefn] CSS file not found:', cssPath);
  }

  // Write the generated virtual module to .stylefn/ directory
  const generatedDir = path.resolve(projectRoot, '.stylefn');
  fs.mkdirSync(generatedDir, { recursive: true });

  const cssVarsFile = path.join(generatedDir, 'css-vars.js');
  fs.writeFileSync(
    cssVarsFile,
    `// Auto-generated by react-native-stylefn — do not edit\nmodule.exports = ${JSON.stringify(
      parsedCss,
      null,
      2
    )};\n`
  );

  // Add .stylefn to .gitignore if not already there
  const gitignorePath = path.resolve(projectRoot, '.gitignore');
  if (fs.existsSync(gitignorePath)) {
    const gitignore = fs.readFileSync(gitignorePath, 'utf8');
    if (!gitignore.includes('.stylefn')) {
      fs.appendFileSync(
        gitignorePath,
        '\n# react-native-stylefn generated\n.stylefn/\n'
      );
    }
  }

  // Wrap the resolver to map react-native-stylefn/css-vars → generated file
  const existingResolver = config.resolver?.resolveRequest;

  return {
    ...config,
    resolver: {
      ...config.resolver,
      resolveRequest: (context, moduleName, platform) => {
        if (moduleName === 'react-native-stylefn/css-vars') {
          return {
            filePath: cssVarsFile,
            type: 'sourceFile',
          };
        }
        if (existingResolver) {
          return existingResolver(context, moduleName, platform);
        }
        return context.resolveRequest(context, moduleName, platform);
      },
    },
  };
}

module.exports = { withStyleFn };
